### ISSUE TITLE
[Bug] Android back button exits app instead of taking me to the last page

### ISSUE THREAD

**Issue by hel1ow0r1d** [justynth/Friend_Builder#117]
When I press the Android back button instead of the app back button, it always exits the app. With taller screens these days, it's easier to go back with the Android back button rather than reaching the back button at the top left corner of the app, instead of just exiting the app. The back button should only exit from the app when in the home menu.

**Comment by btackett3** [comment]
Thanks for testing the app.  Would you say this negatively affects your user experience?

**Comment by hel1ow0r1d** [comment]
Kind of. Since all the other apps behave that way, it sort of becomes like a muscle memory and you know what to expect. Initially, I got really confused and frustrated by it (I got a new Android update yesterday and thought it was Android's fault), only to later realize that the developer actually need to implement it, and it's not Android's fault. It's a minor issue, but it does somewhat affect the UX.
