### ISSUE TITLE
[Bug] End events you did not create.

### ISSUE THREAD

**Issue by rmredder** [justynth/Friend_Builder#151]
I created an event with one account and then used a different account to look at the first users events. The event popup box showed the "End event" button and allowed me to use it to end the event. I'm assuming this is not intended? It would make sense that only the person who created the event should be able to end it.

To clarify:
Navigated to "Users Near me"
Found a user who had an active event
Clicked end event on their event.
Went back to look at event again and event was now inactive.

**Comment by btackett3** [comment]
Thank you for the thorough testing!  That is indeed not intended.
